import type { Team, Task, Message } from "../types/index.js";

export function generateMockTeams(): Team[] {
  return [
    {
      id: "feature-auth",
      name: "feature-auth",
      description: "Building authentication system",
      members: [
        { name: "team-lead", agentId: "agent-001", agentType: "lead", status: "active" as const, currentTask: "Configuring OAuth2 providers" },
        { name: "backend-dev", agentId: "agent-002", agentType: "developer", status: "active" as const, currentTask: "Implementing JWT token service" },
        { name: "frontend-dev", agentId: "agent-003", agentType: "developer", status: "idle" as const },
        { name: "tester", agentId: "agent-004", agentType: "tester", status: "idle" as const },
      ],
      taskCount: 8,
      activeTasks: 3,
      status: "active",
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      lastActivityAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(), // 2 min ago
    },
    {
      id: "refactor-api",
      name: "refactor-api",
      description: "API refactoring and optimization",
      members: [
        { name: "architect", agentId: "agent-010", agentType: "lead", status: "active" as const, currentTask: "Reviewing API audit" },
        { name: "dev-1", agentId: "agent-011", agentType: "developer", status: "active" as const, currentTask: "Refactoring API response format" },
        { name: "dev-2", agentId: "agent-012", agentType: "developer", status: "active" as const, currentTask: "Implementing validation middleware" },
      ],
      taskCount: 5,
      activeTasks: 2,
      status: "active",
      createdAt: new Date(Date.now() - 7200000).toISOString(),
      lastActivityAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(), // 3 min ago
    },
    {
      id: "docs-update",
      name: "docs-update",
      description: "Documentation overhaul",
      members: [
        { name: "writer", agentId: "agent-020", agentType: "writer", status: "idle" as const },
        { name: "reviewer", agentId: "agent-021", agentType: "reviewer", status: "idle" as const },
      ],
      taskCount: 3,
      activeTasks: 0,
      status: "idle",
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      lastActivityAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago — stale
    },
  ];
}

export function generateMockTasks(): Task[] {
  return [
    // feature-auth tasks
    {
      id: "1",
      subject: "Design authentication database schema",
      description:
        "Create the database schema for users, sessions, and tokens. Include proper indexes and constraints.",
      status: "completed",
      owner: "backend-dev",
      teamId: "feature-auth",
      blocks: ["2", "3"],
      blockedBy: [],
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      updatedAt: new Date(Date.now() - 1800000).toISOString(),
    },
    {
      id: "2",
      subject: "Implement JWT token generation and validation",
      description:
        "Build the JWT service with access and refresh token support. Include token rotation.",
      status: "in_progress",
      owner: "backend-dev",
      teamId: "feature-auth",
      blocks: ["5"],
      blockedBy: ["1"],
      activeForm: "Implementing JWT token service",
      createdAt: new Date(Date.now() - 3000000).toISOString(),
      updatedAt: new Date(Date.now() - 600000).toISOString(),
    },
    {
      id: "3",
      subject: "Build login and registration API endpoints",
      description:
        "Create POST /auth/login, POST /auth/register, POST /auth/refresh, POST /auth/logout endpoints.",
      status: "in_progress",
      owner: "backend-dev",
      teamId: "feature-auth",
      blocks: ["6"],
      blockedBy: ["1"],
      activeForm: "Building auth API endpoints",
      createdAt: new Date(Date.now() - 3000000).toISOString(),
      updatedAt: new Date(Date.now() - 300000).toISOString(),
    },
    {
      id: "4",
      subject: "Design login page UI mockups",
      description: "Create the login and registration page designs with form validation states.",
      status: "completed",
      owner: "frontend-dev",
      teamId: "feature-auth",
      blocks: ["6"],
      blockedBy: [],
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      updatedAt: new Date(Date.now() - 2400000).toISOString(),
    },
    {
      id: "5",
      subject: "Write authentication middleware",
      description: "Create Express middleware that validates JWT tokens on protected routes.",
      status: "pending",
      teamId: "feature-auth",
      blocks: ["7"],
      blockedBy: ["2"],
      createdAt: new Date(Date.now() - 2400000).toISOString(),
    },
    {
      id: "6",
      subject: "Implement login and registration forms",
      description: "Build the React forms with validation, error handling, and loading states.",
      status: "pending",
      owner: "frontend-dev",
      teamId: "feature-auth",
      blocks: ["7"],
      blockedBy: ["3", "4"],
      createdAt: new Date(Date.now() - 2400000).toISOString(),
    },
    {
      id: "7",
      subject: "Integration testing for auth flow",
      description: "End-to-end tests for the full authentication flow: register, login, protected routes, logout.",
      status: "pending",
      owner: "tester",
      teamId: "feature-auth",
      blocks: [],
      blockedBy: ["5", "6"],
      createdAt: new Date(Date.now() - 2400000).toISOString(),
    },
    {
      id: "8",
      subject: "Set up OAuth2 provider configuration",
      description: "Configure Google and GitHub OAuth2 providers for social login.",
      status: "in_progress",
      owner: "team-lead",
      teamId: "feature-auth",
      blocks: [],
      blockedBy: [],
      activeForm: "Configuring OAuth2 providers",
      createdAt: new Date(Date.now() - 1800000).toISOString(),
      updatedAt: new Date(Date.now() - 120000).toISOString(),
    },
    // refactor-api tasks
    {
      id: "9",
      subject: "Audit existing API endpoints",
      description: "Document all current endpoints, their usage patterns, and identify inconsistencies.",
      status: "completed",
      owner: "architect",
      teamId: "refactor-api",
      blocks: ["10", "11"],
      blockedBy: [],
      createdAt: new Date(Date.now() - 7200000).toISOString(),
      updatedAt: new Date(Date.now() - 5400000).toISOString(),
    },
    {
      id: "10",
      subject: "Refactor response format to use envelope pattern",
      description: "Standardize all API responses to use { data, meta, error } envelope format.",
      status: "in_progress",
      owner: "dev-1",
      teamId: "refactor-api",
      blocks: ["13"],
      blockedBy: ["9"],
      activeForm: "Refactoring API response format",
      createdAt: new Date(Date.now() - 5400000).toISOString(),
      updatedAt: new Date(Date.now() - 900000).toISOString(),
    },
    {
      id: "11",
      subject: "Implement request validation middleware",
      description: "Add Zod-based request validation for all endpoints using shared schemas.",
      status: "in_progress",
      owner: "dev-2",
      teamId: "refactor-api",
      blocks: ["13"],
      blockedBy: ["9"],
      activeForm: "Implementing validation middleware",
      createdAt: new Date(Date.now() - 5400000).toISOString(),
      updatedAt: new Date(Date.now() - 450000).toISOString(),
    },
    {
      id: "12",
      subject: "Add rate limiting to all endpoints",
      description: "Configure rate limiting per IP and per user, with different limits for auth vs public endpoints.",
      status: "pending",
      teamId: "refactor-api",
      blocks: [],
      blockedBy: [],
      createdAt: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      id: "13",
      subject: "Update API documentation",
      description: "Regenerate OpenAPI spec and update README with new response formats and validation rules.",
      status: "pending",
      owner: "architect",
      teamId: "refactor-api",
      blocks: [],
      blockedBy: ["10", "11"],
      createdAt: new Date(Date.now() - 3600000).toISOString(),
    },
    // docs-update tasks
    {
      id: "14",
      subject: "Outline documentation structure",
      description: "Create a table of contents and outline for the new documentation.",
      status: "completed",
      owner: "writer",
      teamId: "docs-update",
      blocks: ["15"],
      blockedBy: [],
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 72000000).toISOString(),
    },
    {
      id: "15",
      subject: "Write getting started guide",
      description: "Create a comprehensive getting started guide with examples and troubleshooting section.",
      status: "completed",
      owner: "writer",
      teamId: "docs-update",
      blocks: ["16"],
      blockedBy: ["14"],
      createdAt: new Date(Date.now() - 72000000).toISOString(),
      updatedAt: new Date(Date.now() - 43200000).toISOString(),
    },
    {
      id: "16",
      subject: "Review and publish documentation",
      description: "Final review pass and publish to documentation site.",
      status: "completed",
      owner: "reviewer",
      teamId: "docs-update",
      blocks: [],
      blockedBy: ["15"],
      createdAt: new Date(Date.now() - 43200000).toISOString(),
      updatedAt: new Date(Date.now() - 3600000).toISOString(),
    },
  ];
}

export function generateMockMessages(): Message[] {
  return [
    {
      id: "msg-1",
      teamId: "feature-auth",
      type: "message",
      sender: "team-lead",
      recipient: "backend-dev",
      content: "The database schema looks good. Please proceed with the JWT implementation.",
      summary: "Schema approved, proceed with JWT",
      timestamp: new Date(Date.now() - 1800000).toISOString(),
    },
    {
      id: "msg-2",
      teamId: "feature-auth",
      type: "broadcast",
      sender: "team-lead",
      content:
        "Team standup: We are on track. Backend is working on JWT tokens and auth endpoints. Frontend has completed the UI mockups.",
      summary: "Team standup update",
      timestamp: new Date(Date.now() - 1200000).toISOString(),
    },
    {
      id: "msg-3",
      teamId: "feature-auth",
      type: "message",
      sender: "frontend-dev",
      recipient: "backend-dev",
      content:
        "What response format should I expect from the login endpoint? I need to know the token structure for the client.",
      summary: "Asking about login response format",
      timestamp: new Date(Date.now() - 900000).toISOString(),
    },
    {
      id: "msg-4",
      teamId: "feature-auth",
      type: "message",
      sender: "backend-dev",
      recipient: "frontend-dev",
      content:
        'Login will return { accessToken, refreshToken, user: { id, email, name } }. Access token expires in 15 minutes.',
      summary: "Login response format details",
      timestamp: new Date(Date.now() - 600000).toISOString(),
    },
    {
      id: "msg-5",
      teamId: "refactor-api",
      type: "message",
      sender: "architect",
      recipient: "dev-1",
      content:
        "Make sure the envelope pattern includes a `pagination` field in the `meta` object for list endpoints.",
      summary: "Add pagination to envelope meta",
      timestamp: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      id: "msg-6",
      teamId: "refactor-api",
      type: "broadcast",
      sender: "architect",
      content:
        "Heads up: I have updated the shared Zod schemas in the types package. Please pull the latest changes.",
      summary: "Shared schemas updated, pull latest",
      timestamp: new Date(Date.now() - 1800000).toISOString(),
    },
  ];
}
